name: Build and Release macOS App

on:
  release:
    types: [created] # Trigger workflow when a new release is created

jobs:
  build:
    permissions: write-all
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            architecture: x86_64
          - target: aarch64-apple-darwin
            architecture: arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Select Xcode 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Install dependencies (if any)
        run: brew install hdf5

      - name: Build macOS app for ${{ matrix.target }}
        run: |
          echo "Building for ${{ matrix.architecture }}..."
          xcodebuild clean build \
            -scheme HDF5QL \
            -configuration Release \
            -destination "platform=macOS,arch=${{ matrix.architecture }}" \
            BUILD_DIR=./build \
            | tee build.log

      - name: Package the .app into a .zip file
        run: |
          cd build/Release/
          zip -r HDF5QL-${{ matrix.target }}.app.zip HDF5QL.app
          mv HDF5QL-${{ matrix.target }}.app.zip $GITHUB_WORKSPACE/

      - name: Upload .zip of .app
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: HDF5QL-${{ matrix.target }}.app.zip
          asset_name: HDF5QL-${{ matrix.target }}.app.zip
          asset_content_type: application/zip
