name: Build and Release macOS App

on:
  release:
    types: [created] # Trigger workflow when a new release is created

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        architecture: [x86_64, arm64]  # Build for both x86_64 and arm64 architectures

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Select Xcode 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Install dependencies (if any)
        run: brew install hdf5

      - name: Build macOS app for ${{ matrix.architecture }}
        run: |
          echo "Building for ${{ matrix.architecture }}..."
          xcodebuild clean build \
            -scheme HDF5QL \
            -configuration Release \
            -destination "platform=macOS,arch=${{ matrix.architecture }}" \
            BUILD_DIR=./build \
            | tee build.log

      - name: Package the .app into a .zip file
        run: |
          ARCHIVE_PATH="./build/Release/HDF5QL.app"
          ZIP_PATH="./build/HDF5QL-${{ matrix.architecture }}.zip"
          zip -r $ZIP_PATH $ARCHIVE_PATH

      - name: Extract and package the .appex extension
        run: |
          echo "🔍 Searching for .appex bundle..."
          appex_path=$(find ./build -type d -name "*.appex" | head -n 1)
          
          if [ -d "$appex_path" ]; then
            echo "✅ Found .appex at: $appex_path"
            zip -r "./build/HDF5QLExtension-${{ matrix.architecture }}.zip" "$appex_path"
          else
            echo "❌ .appex bundle not found. Check build configuration or path."
            exit 1
          fi

      - name: Upload macOS app and extension to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          files: |
            ./build/HDF5QL-${{ matrix.architecture }}.zip
            ./build/HDF5QLExtension-${{ matrix.architecture }}.zip
